---
# tasks file for ec2m
- name: start multiple instances
  amazon.aws.ec2_instance:
    instance_type: t2.micro
    image_id: ami-0ad21ae1d0696ad58
    exact_count: 5
    region: ap-south-1
    aws_access_key: "{{ec2_access_key}}"  # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
    vpc_subnet_id: subnet-02b4f4dedb38c458d
    network:
      assign_public_ip: true
      security_group: default
