---
# tasks file for ec2
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "public-compute-instance"
    key_name: "apsouth"
    vpc_subnet_id: subnet-02b4f4dedb38c458d
    instance_type: t2.micro
    security_group: default
    region: ap-south-1
    aws_access_key: "{{ec2_access_key}}"  # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined 
    network:
      assign_public_ip: true
    image_id: ami-0ad21ae1d0696ad58
    tags:
      Environment: Testin
